updated the stage Git Secrets Scan

diff --git a/ci-cd/jenkins/Jenkinsfile b/ci-cd/jenkins/Jenkinsfile
--- a/ci-cd/jenkins/Jenkinsfile
+++ b/ci-cd/jenkins/Jenkinsfile
@@ -90,8 +90,10 @@ pipeline {
                         sh '''
                             # Install git-secrets if not present
                             if ! command -v git-secrets &> /dev/null; then
-                                git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets
-                                cd /tmp/git-secrets && make install PREFIX=/usr/local || echo "Git secrets install failed"
+                                rm -rf /tmp/git-secrets-${BUILD_NUMBER}
+                                git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets-${BUILD_NUMBER}
+                                cd /tmp/git-secrets-${BUILD_NUMBER} && make install PREFIX=$(pwd)/bin || echo "Git secrets install failed"
+                                export PATH=$PATH:/tmp/git-secrets-${BUILD_NUMBER}/bin
                             fi
                             
                             # Scan for secrets
